describe("systemadminsupport", () => {
  it("tests systemadminsupport", () => {
    cy.viewport(1468, 968); 
    cy.visit("https://oms-uat.test.uco.com/login/");
    cy.get("#username").click();
    cy.get("#username").type("test");
    cy.get("#password").click();
    cy.get("#password").type("dummy");
    cy.get("div:nth-of-type(4) > input").click();
    cy.location("href").should("eq", "https://oms-uat.test.uco.com/");
    cy.get("div.nav-collapse > ul > li:nth-of-type(12) > a").click();
    cy.get("li.open li:nth-of-type(3) > a").click();
    cy.location("href").should("eq", "https://oms-uat.test.uco.com/platform_auth/");
    cy.get("div.nav-collapse > ul > li:nth-of-type(12) > a").click();
    cy.get("li.open li:nth-of-type(6) > a").click();
    cy.location("href").should("eq", "https://oms-uat.test.uco.com/stress/");
    cy.get("div.nav-collapse > ul > li:nth-of-type(12) > a").click();
    cy.get("li.open li:nth-of-type(7) > a").click();
    cy.location("href").should("eq", "https://oms-uat.test.uco.com/config/approver");
    cy.get("div.nav-collapse > ul > li:nth-of-type(12) > a").click();
    cy.get("li.active li:nth-of-type(8) > a").click();
    cy.location("href").should("eq", "https://oms-uat.test.uco.com/platform/list");
    cy.get("div.nav-collapse > ul > li:nth-of-type(12) > a").click();
    cy.get("li.open li:nth-of-type(10) > a").click();
    cy.location("href").should("eq", "https://oms-uat.test.uco.com/message_queue/");
    cy.get("div.nav-collapse > ul > li:nth-of-type(12) > a").click();
    cy.get("li.active li:nth-of-type(11) > a").click();
    cy.location("href").should("eq", "https://oms-uat.test.uco.com/message_queue/parent");
    cy.get("div.nav-collapse > ul > li:nth-of-type(12) > a").click();
    cy.get("li.open > ul > li:nth-of-type(12) > a").click();
    cy.location("href").should("eq", "https://oms-uat.test.uco.com/reset_queuebetter/");
    cy.get("div.nav-collapse > ul > li:nth-of-type(12) > a").click();
    cy.get("li.open li:nth-of-type(14) > a").click();
    cy.location("href").should("eq", "https://oms-uat.test.uco.com/alram/lists");
    cy.get("div.nav-collapse > ul > li:nth-of-type(12) > a").click();
    cy.get("li.open li:nth-of-type(15) > a").click();
    cy.location("href").should("eq", "https://oms-uat.test.uco.com/easymonitor/lists");
    cy.get("div.nav-collapse > ul > li:nth-of-type(12) > a").click();
    cy.get("li.open li:nth-of-type(18) > a").click();
    cy.location("href").should("eq", "https://oms-uat.test.uco.com/constants/defaultStockTypeOfPlatform");
    cy.get("div.nav-collapse > ul > li:nth-of-type(12) > a").click();
    cy.get("li.open li:nth-of-type(20) > a").click();
    cy.location("href").should("eq", "https://oms-uat.test.uco.com/config/warehouseArea");
    cy.get("div.nav-collapse > ul > li:nth-of-type(12) > a").click();
    cy.get("li.active li:nth-of-type(22) > a").click();
    cy.location("href").should("eq", "https://oms-uat.test.uco.com/diagnose/orderImperativeOperationPage");
    cy.get("div.nav-collapse > ul > li:nth-of-type(12) > a").click();
    cy.get("li.active li:nth-of-type(24) > a").click();
    cy.location("href").should("eq", "https://oms-uat.test.uco.com/diagnose/cancelOrder");
    cy.get("div.nav-collapse > ul > li:nth-of-type(12) > a").click();
    cy.get("li.open li:nth-of-type(26) > a").click();
    cy.location("href").should("eq", "https://oms-uat.test.uco.com/promotion/operation_promotion_limit");
  });
});
